/*
 * Mitgeliefertes Ortsverzeichnis für die Suche (ARCHITECTURE.md Abschnitt 10).
 * Kein externer Dienst, keine API – eine feste, kuratierte Liste von Ländern,
 * Hauptstädten und Regionen, u. a. den Orten der Beispiel-Anomalien. Für den
 * echten Betrieb kann diese Liste später durch einen Auszug aus Natural
 * Earth / GeoNames ersetzt werden (siehe ARCHITECTURE.md Abschnitt 10).
 */
window.ALEPH_ORTE = [
  { "name": "Kyiv", "land": "Ukraine", "lon": 30.52, "lat": 50.45 },
  { "name": "Ukraine", "land": "Ukraine", "lon": 31.0, "lat": 49.0 },
  { "name": "Donetsk", "land": "Ukraine", "lon": 37.8, "lat": 48.0 },
  { "name": "Charkiw", "land": "Ukraine", "lon": 36.23, "lat": 49.99 },
  { "name": "Gaza-Stadt", "land": "Palästinensische Gebiete", "lon": 34.47, "lat": 31.5 },
  { "name": "Khartum", "land": "Sudan", "lon": 32.53, "lat": 15.6 },
  { "name": "Addis Abeba", "land": "Äthiopien", "lon": 38.75, "lat": 9.03 },
  { "name": "Mogadischu", "land": "Somalia", "lon": 45.32, "lat": 2.04 },
  { "name": "Horn von Afrika", "land": "Ostafrika", "lon": 44.0, "lat": 7.0 },
  { "name": "Sahel", "land": "Westafrika", "lon": 5.0, "lat": 14.0 },
  { "name": "Niamey", "land": "Niger", "lon": 2.11, "lat": 13.51 },
  { "name": "Lagos", "land": "Nigeria", "lon": 3.39, "lat": 6.52 },
  { "name": "Kinshasa", "land": "DR Kongo", "lon": 15.27, "lat": -4.44 },
  { "name": "Kongobecken", "land": "Zentralafrika", "lon": 22.0, "lat": -1.0 },
  { "name": "Damaskus", "land": "Syrien", "lon": 36.28, "lat": 33.51 },
  { "name": "Aleppo", "land": "Syrien", "lon": 37.16, "lat": 36.2 },
  { "name": "Gaziantep", "land": "Türkei", "lon": 37.38, "lat": 37.07 },
  { "name": "Teheran", "land": "Iran", "lon": 51.39, "lat": 35.69 },
  { "name": "Neu-Delhi", "land": "Indien", "lon": 77.21, "lat": 28.61 },
  { "name": "Mumbai", "land": "Indien", "lon": 72.88, "lat": 19.08 },
  { "name": "Indus-Becken", "land": "Pakistan", "lon": 70.5, "lat": 27.5 },
  { "name": "Islamabad", "land": "Pakistan", "lon": 73.06, "lat": 33.68 },
  { "name": "Dhaka", "land": "Bangladesch", "lon": 90.41, "lat": 23.81 },
  { "name": "Jakarta", "land": "Indonesien", "lon": 106.85, "lat": -6.21 },
  { "name": "Borneo", "land": "Indonesien", "lon": 114.0, "lat": -1.0 },
  { "name": "Kuala Lumpur", "land": "Malaysia", "lon": 101.69, "lat": 3.14 },
  { "name": "Straße von Malakka", "land": "Südostasien", "lon": 98.7, "lat": 3.5 },
  { "name": "Almaty", "land": "Kasachstan", "lon": 76.91, "lat": 43.24 },
  { "name": "Tengiz", "land": "Kasachstan", "lon": 53.4, "lat": 46.2 },
  { "name": "Peking", "land": "China", "lon": 116.4, "lat": 39.9 },
  { "name": "Madrid", "land": "Spanien", "lon": -3.7, "lat": 40.42 },
  { "name": "Iberische Halbinsel", "land": "Spanien/Portugal", "lon": -4.0, "lat": 40.0 },
  { "name": "Lissabon", "land": "Portugal", "lon": -9.14, "lat": 38.72 },
  { "name": "Berlin", "land": "Deutschland", "lon": 13.4, "lat": 52.52 },
  { "name": "Nördlicher Seeweg", "land": "Arktis", "lon": 90.0, "lat": 75.0 },
  { "name": "Murmansk", "land": "Russland", "lon": 33.08, "lat": 68.97 },
  { "name": "Canberra", "land": "Australien", "lon": 149.13, "lat": -35.28 },
  { "name": "Südost-Australien", "land": "Australien", "lon": 149.5, "lat": -36.5 },
  { "name": "Sydney", "land": "Australien", "lon": 151.21, "lat": -33.87 },
  { "name": "Brasília", "land": "Brasilien", "lon": -47.93, "lat": -15.78 },
  { "name": "Rondônia", "land": "Brasilien", "lon": -62.5, "lat": -9.8 },
  { "name": "Manaus", "land": "Brasilien", "lon": -60.02, "lat": -3.1 },
  { "name": "Amazonas", "land": "Brasilien", "lon": -62.0, "lat": -5.0 },
  { "name": "Caracas", "land": "Venezuela", "lon": -66.9, "lat": 10.5 },
  { "name": "Bogotá", "land": "Kolumbien", "lon": -74.08, "lat": 4.71 },
  { "name": "Mexiko-Stadt", "land": "Mexiko", "lon": -99.13, "lat": 19.43 },
  { "name": "Washington, D.C.", "land": "USA", "lon": -77.04, "lat": 38.91 },
  { "name": "Ottawa", "land": "Kanada", "lon": -75.7, "lat": 45.42 },
  { "name": "London", "land": "Vereinigtes Königreich", "lon": -0.13, "lat": 51.51 },
  { "name": "Paris", "land": "Frankreich", "lon": 2.35, "lat": 48.86 },
  { "name": "Rom", "land": "Italien", "lon": 12.5, "lat": 41.9 },
  { "name": "Kairo", "land": "Ägypten", "lon": 31.24, "lat": 30.04 },
  { "name": "Nairobi", "land": "Kenia", "lon": 36.82, "lat": -1.29 },
  { "name": "Kapstadt", "land": "Südafrika", "lon": 18.42, "lat": -33.92 },
  { "name": "Tokio", "land": "Japan", "lon": 139.69, "lat": 35.69 },
  { "name": "Seoul", "land": "Südkorea", "lon": 126.98, "lat": 37.57 },
  { "name": "Wellington", "land": "Neuseeland", "lon": 174.78, "lat": -41.29 },
  { "name": "Reykjavík", "land": "Island", "lon": -21.94, "lat": 64.15 },
  { "name": "Grönland", "land": "Arktis", "lon": -42.0, "lat": 72.0 }
];
